### ISSUE TITLE
NodeSchool Introducción a JavaScript solo para Mujeres

### ISSUE THREAD

**Issue by davsket** [nodeschool/bogota#4]
Cualquier inquietud que tengas sobre este NodeSchool.
Será realizado usando: [javascripting-es](https://www.npmjs.com/package/javascripting-es)
También nos puedes escribir via [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/bogota?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by manvedu** [comment]
Buenas noches!
Aprovecho el medio ya que tengo una duda. Estoy tratando de terminar learnyounode, me encuentro realizando el ejercicio número 10, y tengo un problema se supone que ya lo pase, pero me aparecen dos errores que no comprendo los cuales me dicen que la conexión no se puedo establecer, esto mismo me aparecía cuando usaba learnyounode run program.js no hice sino asegurar que el process.argv[] fuese un número usando el método Number(), pero cuando hago  learnyounode verify program.js  aunque pasa la solución y empleando la solución propuesta me sigue apareciendo eso, lei por ahí y en consola puse  netstat -lpt pero no aparece el puerto en uso ni nada parecido, no me explico que sea. Tengo un pantallazo. Espero me puedan ayudar y explicar gracias. 
Que tengan feliz noche.

**Comment by julianduque** [comment]
@manvedu puedes compartir el pantallazo del error que tienes?

**Comment by manvedu** [comment]
![ummmm](https://cloud.githubusercontent.com/assets/11188064/7403596/b6efb9d8-ee9c-11e4-9517-9cc84fb136cd.png)

Buenas tardes @julianduque  es este, gracias. 
En el siguiente ejercicio haciéndolo con http también me sale el mismo error, ejercicios 10 y 11.

**Comment by davsket** [comment]
Veo que tienes el mismo código que la solución, pareciera como si tuvieras bloqueados los puertos o algo así. Prueba esta respuesta: http://stackoverflow.com/questions/14168433/node-js-error-connect-econnrefused a ver si te da más información.

**Comment by julianduque** [comment]
@manvedu donde estas ejecutando este ejercicio? En tu computador, o en Cloud9 o Codio?
